### ISSUE TITLE
Image does not display when width / height are set to auto

### ISSUE THREAD

**Issue by ValtechDeBruyneYves** [Frontify/frontify-aem-connector#10]
- if a height is given, add height=123 and if no height is given, the parameter must be dropped.
- same for width
- restrict user input to 0 <= x <= 4096

For backwards compatibility the API supports `=auto`

**Comment by le0daniel** [comment]
Image worker URL: possible parameters with available values

- format: `String` possible values: png,mp4,jpg,jpeg,gif,webp
- height: `Int` possible values 0 < X <= 4096 
- width: `Int` possible values 0 < X <= 4096

If not available, the parameter needs to be dropped. We added backwards compatibility for `auto` and I ll do the same if the width | height is bigger than 4096. It will then just fallback to 4096. This is so that we do not break current users.
